import type { CharacterKey, WeaponKey } from "./types";

export type ClassKey =
  | "brawler"
  | "bandana"
  | "boomerang"
  | "soldier"
  | "ninja"
  | "assassin"
  | "pirate"
  | "viking"
  | "knight"
  | "gladiator"
  | "hunter"
  | "ranger"
  | "mage"
  | "witch"
  | "druid"
  | "shaman"
  | "monk"
  | "paladin"
  | "cleric"
  | "engineer"
  | "alchemist"
  | "chemist"
  | "doctor"
  | "psycho"
  | "jester"
  | "clown"
  | "ghost"
  | "cultist"
  | "demon"
  | "reaper";

export interface ClassBuff {
  label: string;
  value: string;
  tone?: "good" | "bad" | "neutral";
}

export interface ClassDef {
  key: ClassKey;
  name: string;
  blurb: string;
  /** Visual skin borrowed from the hero roster. */
  skin: CharacterKey;
  weapon: WeaponKey;
  hp: number;
  speed: number;
  damage: number;
  /** Starting turrets deployed around the player. */
  turrets: number;
  /** Turret weapon when turrets > 0. */
  turretWeapon: WeaponKey;
  /** Extra crit chance added on top of base 5%. */
  crit: number;
  /** Lifesteal added on top of base 0. */
  lifesteal: number;
  /** Extra starting max HP multiplier (1 = none). */
  hpMult: number;
  /** Movement speed multiplier (1 = none). */
  speedMult: number;
  /** Damage multiplier (1 = none). */
  damageMult: number;
  /** Starting shop materials bonus. */
  startingMaterials: number;
  color: string;
  buffs: ClassBuff[];
}

const ALL_WEAPONS: WeaponKey[] = [
  "pistol",
  "rifle",
  "shotgun",
  "minigun",
  "smg",
  "sniper",
  "flak",
  "plasma",
  "rocket",
  "laser",
  "crossbow",
  "chain",
  "revolver",
  "carbine",
  "autoshotgun",
  "grenadier",
  "railgun",
  "vulcan",
];

function w(idx: number): WeaponKey {
  return ALL_WEAPONS[idx % ALL_WEAPONS.length]!;
}

export const CLASSES: Record<ClassKey, ClassDef> = {
  brawler: {
    key: "brawler",
    name: "Brawler",
    blurb: "Raw muscle. Punches harder, shrugs off hits, starts with a shotgun.",
    skin: "warchief",
    weapon: "shotgun",
    hp: 130,
    speed: 245,
    damage: 1.25,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1.15,
    speedMult: 0.95,
    damageMult: 1.15,
    startingMaterials: 0,
    color: "#ff7b4d",
    buffs: [
      { label: "HP", value: "+15%", tone: "good" },
      { label: "Damage", value: "+15%", tone: "good" },
      { label: "Speed", value: "-5%", tone: "bad" },
    ],
  },
  bandana: {
    key: "bandana",
    name: "Bandana",
    blurb: "A nimble scavenger with a fast trigger and a nose for loot.",
    skin: "punk",
    weapon: "smg",
    hp: 92,
    speed: 300,
    damage: 1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.05,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1.08,
    damageMult: 1,
    startingMaterials: 20,
    color: "#7bf2a8",
    buffs: [
      { label: "Speed", value: "+8%", tone: "good" },
      { label: "Crit", value: "+5%", tone: "good" },
      { label: "Materials", value: "+20", tone: "good" },
    ],
  },
  boomerang: {
    key: "boomerang",
    name: "Boomerang",
    blurb: "Ricocheting shots always come back. High pierce, high speed.",
    skin: "bald",
    weapon: "crossbow",
    hp: 95,
    speed: 285,
    damage: 1.15,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1.05,
    damageMult: 1.1,
    startingMaterials: 0,
    color: "#c77dff",
    buffs: [
      { label: "Pierce", value: "+2", tone: "good" },
      { label: "Speed", value: "+5%", tone: "good" },
    ],
  },
  soldier: {
    key: "soldier",
    name: "Soldier",
    blurb: "Disciplined rifle work. Starts with extra ammo and a steady hand.",
    skin: "spike",
    weapon: "rifle",
    hp: 110,
    speed: 270,
    damage: 1.1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1.05,
    speedMult: 1,
    damageMult: 1.1,
    startingMaterials: 10,
    color: "#5ec8ff",
    buffs: [
      { label: "HP", value: "+5%", tone: "good" },
      { label: "Damage", value: "+10%", tone: "good" },
      { label: "Materials", value: "+10", tone: "good" },
    ],
  },
  ninja: {
    key: "ninja",
    name: "Ninja",
    blurb: "Strikes from nowhere. Massive crit chance, fragile frame.",
    skin: "reaper",
    weapon: "pistol",
    hp: 78,
    speed: 320,
    damage: 1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.2,
    lifesteal: 0,
    hpMult: 0.9,
    speedMult: 1.12,
    damageMult: 1,
    startingMaterials: 0,
    color: "#9fd8ff",
    buffs: [
      { label: "Crit", value: "+20%", tone: "good" },
      { label: "Speed", value: "+12%", tone: "good" },
      { label: "HP", value: "-10%", tone: "bad" },
    ],
  },
  assassin: {
    key: "assassin",
    name: "Assassin",
    blurb: "One shot, one kill. Sniper specialist with lethal precision.",
    skin: "reaper",
    weapon: "sniper",
    hp: 82,
    speed: 295,
    damage: 1.35,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.12,
    lifesteal: 0,
    hpMult: 0.95,
    speedMult: 1.05,
    damageMult: 1.2,
    startingMaterials: 0,
    color: "#b98bff",
    buffs: [
      { label: "Damage", value: "+20%", tone: "good" },
      { label: "Crit", value: "+12%", tone: "good" },
      { label: "HP", value: "-5%", tone: "bad" },
    ],
  },
  pirate: {
    key: "pirate",
    name: "Pirate",
    blurb: "Blunderbuss in one hand, coin pouch in the other.",
    skin: "crown",
    weapon: "shotgun",
    hp: 105,
    speed: 275,
    damage: 1.15,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1,
    damageMult: 1.15,
    startingMaterials: 40,
    color: "#ffd166",
    buffs: [
      { label: "Damage", value: "+15%", tone: "good" },
      { label: "Materials", value: "+40", tone: "good" },
    ],
  },
  viking: {
    key: "viking",
    name: "Viking",
    blurb: "A tanky berserker that heals with every kill.",
    skin: "warchief",
    weapon: "chain",
    hp: 145,
    speed: 250,
    damage: 1.2,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0.06,
    hpMult: 1.2,
    speedMult: 0.95,
    damageMult: 1.2,
    startingMaterials: 0,
    color: "#ff9a5c",
    buffs: [
      { label: "HP", value: "+20%", tone: "good" },
      { label: "Damage", value: "+20%", tone: "good" },
      { label: "Lifesteal", value: "+6%", tone: "good" },
      { label: "Speed", value: "-5%", tone: "bad" },
    ],
  },
  knight: {
    key: "knight",
    name: "Knight",
    blurb: "Heavy armour, steady carbine. Hard to kill, hard to stop.",
    skin: "templar",
    weapon: "carbine",
    hp: 140,
    speed: 255,
    damage: 1.15,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1.2,
    speedMult: 0.97,
    damageMult: 1.15,
    startingMaterials: 0,
    color: "#9fd8ff",
    buffs: [
      { label: "HP", value: "+20%", tone: "good" },
      { label: "Damage", value: "+15%", tone: "good" },
      { label: "Speed", value: "-3%", tone: "bad" },
    ],
  },
  gladiator: {
    key: "gladiator",
    name: "Gladiator",
    blurb: "Crowd-pleasing cleaver swings. Bonus damage, bonus health.",
    skin: "templar",
    weapon: "cleaver",
    hp: 125,
    speed: 265,
    damage: 1.3,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1.1,
    speedMult: 1,
    damageMult: 1.3,
    startingMaterials: 0,
    color: "#ff7b4d",
    buffs: [
      { label: "HP", value: "+10%", tone: "good" },
      { label: "Damage", value: "+30%", tone: "good" },
    ],
  },
  hunter: {
    key: "hunter",
    name: "Hunter",
    blurb: "Tracks prey across the arena. Starts with a loyal auto-turret.",
    skin: "bald",
    weapon: "rifle",
    hp: 100,
    speed: 280,
    damage: 1.1,
    turrets: 1,
    turretWeapon: "pistol",
    crit: 0.05,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1.02,
    damageMult: 1.1,
    startingMaterials: 0,
    color: "#7bf2a8",
    buffs: [
      { label: "Turret", value: "1", tone: "good" },
      { label: "Crit", value: "+5%", tone: "good" },
      { label: "Speed", value: "+2%", tone: "good" },
    ],
  },
  ranger: {
    key: "ranger",
    name: "Ranger",
    blurb: "Long-range precision. Fast feet and a vulcan rifle.",
    skin: "bald",
    weapon: "vulcan",
    hp: 95,
    speed: 300,
    damage: 1.1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.08,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1.08,
    damageMult: 1.1,
    startingMaterials: 0,
    color: "#5ec8ff",
    buffs: [
      { label: "Speed", value: "+8%", tone: "good" },
      { label: "Crit", value: "+8%", tone: "good" },
    ],
  },
  mage: {
    key: "mage",
    name: "Mage",
    blurb: "Arcane plasma bolts and faster projectiles.",
    skin: "oracle",
    weapon: "plasma",
    hp: 88,
    speed: 275,
    damage: 1.2,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 0.95,
    speedMult: 1,
    damageMult: 1.2,
    startingMaterials: 0,
    color: "#c77dff",
    buffs: [
      { label: "Damage", value: "+20%", tone: "good" },
      { label: "Proj Speed", value: "+15%", tone: "good" },
      { label: "HP", value: "-5%", tone: "bad" },
    ],
  },
  witch: {
    key: "witch",
    name: "Witch",
    blurb: "Cursed rounds explode on impact and drain life.",
    skin: "oracle",
    weapon: "laser",
    hp: 85,
    speed: 278,
    damage: 1.15,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0.05,
    hpMult: 0.95,
    speedMult: 1.02,
    damageMult: 1.15,
    startingMaterials: 0,
    color: "#b98bff",
    buffs: [
      { label: "Damage", value: "+15%", tone: "good" },
      { label: "Lifesteal", value: "+5%", tone: "good" },
      { label: "Explosive", value: "+1", tone: "good" },
    ],
  },
  druid: {
    key: "druid",
    name: "Druid",
    blurb: "Nature's wrath. Two small turrets sprout at the start.",
    skin: "sprout",
    weapon: "crossbow",
    hp: 105,
    speed: 270,
    damage: 1,
    turrets: 2,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1.05,
    speedMult: 1,
    damageMult: 1,
    startingMaterials: 0,
    color: "#7bf2a8",
    buffs: [
      { label: "Turrets", value: "2", tone: "good" },
      { label: "HP", value: "+5%", tone: "good" },
    ],
  },
  shaman: {
    key: "shaman",
    name: "Shaman",
    blurb: "Spirits lend a hand. Starts with a turret and extra crit.",
    skin: "sprout",
    weapon: "revolver",
    hp: 98,
    speed: 275,
    damage: 1.05,
    turrets: 1,
    turretWeapon: "rifle",
    crit: 0.08,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1,
    damageMult: 1.05,
    startingMaterials: 0,
    color: "#ffd166",
    buffs: [
      { label: "Turret", value: "1", tone: "good" },
      { label: "Crit", value: "+8%", tone: "good" },
    ],
  },
  monk: {
    key: "monk",
    name: "Monk",
    blurb: "Calm, fast, and hard to hit. Punches out rapid rounds.",
    skin: "sprout",
    weapon: "minigun",
    hp: 90,
    speed: 315,
    damage: 1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.06,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1.1,
    damageMult: 1,
    startingMaterials: 0,
    color: "#ff7b4d",
    buffs: [
      { label: "Speed", value: "+10%", tone: "good" },
      { label: "Crit", value: "+6%", tone: "good" },
    ],
  },
  paladin: {
    key: "paladin",
    name: "Paladin",
    blurb: "Holy tank with a turret and heavy health pool.",
    skin: "templar",
    weapon: "rifle",
    hp: 155,
    speed: 250,
    damage: 1.1,
    turrets: 1,
    turretWeapon: "rifle",
    crit: 0,
    lifesteal: 0.04,
    hpMult: 1.25,
    speedMult: 0.95,
    damageMult: 1.1,
    startingMaterials: 0,
    color: "#ffd166",
    buffs: [
      { label: "HP", value: "+25%", tone: "good" },
      { label: "Turret", value: "1", tone: "good" },
      { label: "Lifesteal", value: "+4%", tone: "good" },
      { label: "Speed", value: "-5%", tone: "bad" },
    ],
  },
  cleric: {
    key: "cleric",
    name: "Cleric",
    blurb: "Heals by dealing damage. Starts with strong lifesteal.",
    skin: "seraph",
    weapon: "pistol",
    hp: 110,
    speed: 270,
    damage: 1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0.12,
    hpMult: 1.05,
    speedMult: 1,
    damageMult: 1,
    startingMaterials: 0,
    color: "#9fd8ff",
    buffs: [
      { label: "Lifesteal", value: "+12%", tone: "good" },
      { label: "HP", value: "+5%", tone: "good" },
    ],
  },
  engineer: {
    key: "engineer",
    name: "Engineer",
    blurb: "Builds three turrets at the start. Let the machines fight.",
    skin: "spike",
    weapon: "rifle",
    hp: 100,
    speed: 265,
    damage: 1,
    turrets: 3,
    turretWeapon: "smg",
    crit: 0,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1,
    damageMult: 1,
    startingMaterials: 30,
    color: "#5ec8ff",
    buffs: [
      { label: "Turrets", value: "3", tone: "good" },
      { label: "Materials", value: "+30", tone: "good" },
    ],
  },
  alchemist: {
    key: "alchemist",
    name: "Alchemist",
    blurb: "Volatile grenades and extra explosive damage.",
    skin: "oracle",
    weapon: "grenadier",
    hp: 95,
    speed: 275,
    damage: 1.1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1,
    damageMult: 1.1,
    startingMaterials: 15,
    color: "#7bf2a8",
    buffs: [
      { label: "Explosive", value: "+2", tone: "good" },
      { label: "Damage", value: "+10%", tone: "good" },
      { label: "Materials", value: "+15", tone: "good" },
    ],
  },
  chemist: {
    key: "chemist",
    name: "Chemist",
    blurb: "Coated in corrosive sludge. Bullets pierce and linger.",
    skin: "oracle",
    weapon: "flak",
    hp: 100,
    speed: 270,
    damage: 1.05,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1,
    damageMult: 1.05,
    startingMaterials: 0,
    color: "#b98bff",
    buffs: [
      { label: "Pierce", value: "+1", tone: "good" },
      { label: "Damage", value: "+5%", tone: "good" },
    ],
  },
  doctor: {
    key: "doctor",
    name: "Doctor",
    blurb: "Keeps themselves alive with every shot.",
    skin: "seraph",
    weapon: "pistol",
    hp: 105,
    speed: 275,
    damage: 1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0.08,
    hpMult: 1.05,
    speedMult: 1,
    damageMult: 1,
    startingMaterials: 0,
    color: "#9fd8ff",
    buffs: [
      { label: "Lifesteal", value: "+8%", tone: "good" },
      { label: "HP", value: "+5%", tone: "good" },
    ],
  },
  psycho: {
    key: "psycho",
    name: "Psycho",
    blurb: "Unhinged rate of fire. More bullets, more chaos.",
    skin: "punk",
    weapon: "minigun",
    hp: 85,
    speed: 290,
    damage: 1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.1,
    lifesteal: 0,
    hpMult: 0.9,
    speedMult: 1.05,
    damageMult: 1,
    startingMaterials: 0,
    color: "#ff6ad5",
    buffs: [
      { label: "Fire Rate", value: "+15%", tone: "good" },
      { label: "Crit", value: "+10%", tone: "good" },
      { label: "HP", value: "-10%", tone: "bad" },
    ],
  },
  jester: {
    key: "jester",
    name: "Jester",
    blurb: "Random crits, random joy. Starts with a rocket launcher.",
    skin: "punk",
    weapon: "rocket",
    hp: 95,
    speed: 285,
    damage: 1.1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.15,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1.02,
    damageMult: 1.1,
    startingMaterials: 0,
    color: "#ff7b4d",
    buffs: [
      { label: "Crit", value: "+15%", tone: "good" },
      { label: "Damage", value: "+10%", tone: "good" },
    ],
  },
  clown: {
    key: "clown",
    name: "Clown",
    blurb: "Honk honk. Explosive entry with extra boom.",
    skin: "punk",
    weapon: "grenadier",
    hp: 100,
    speed: 275,
    damage: 1.05,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1,
    damageMult: 1.05,
    startingMaterials: 0,
    color: "#ff9a5c",
    buffs: [
      { label: "Explosive", value: "+2", tone: "good" },
      { label: "Damage", value: "+5%", tone: "good" },
    ],
  },
  ghost: {
    key: "ghost",
    name: "Ghost",
    blurb: "Hard to see, harder to hit. Fragile but blazing fast.",
    skin: "reaper",
    weapon: "pistol",
    hp: 70,
    speed: 340,
    damage: 1.1,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.1,
    lifesteal: 0,
    hpMult: 0.85,
    speedMult: 1.15,
    damageMult: 1.1,
    startingMaterials: 0,
    color: "#9fd8ff",
    buffs: [
      { label: "Speed", value: "+15%", tone: "good" },
      { label: "Crit", value: "+10%", tone: "good" },
      { label: "HP", value: "-15%", tone: "bad" },
    ],
  },
  cultist: {
    key: "cultist",
    name: "Cultist",
    blurb: "Dark rituals grant lifesteal and a cursed minigun.",
    skin: "oracle",
    weapon: "minigun",
    hp: 95,
    speed: 275,
    damage: 1.05,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0.1,
    hpMult: 1,
    speedMult: 1,
    damageMult: 1.05,
    startingMaterials: 0,
    color: "#b98bff",
    buffs: [
      { label: "Lifesteal", value: "+10%", tone: "good" },
      { label: "Damage", value: "+5%", tone: "good" },
    ],
  },
  demon: {
    key: "demon",
    name: "Demon",
    blurb: "Burns through enemies with a flamethrower rifle.",
    skin: "warchief",
    weapon: "flak",
    hp: 115,
    speed: 270,
    damage: 1.25,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0,
    lifesteal: 0,
    hpMult: 1.1,
    speedMult: 1,
    damageMult: 1.25,
    startingMaterials: 0,
    color: "#ff6b5c",
    buffs: [
      { label: "Damage", value: "+25%", tone: "good" },
      { label: "HP", value: "+10%", tone: "good" },
    ],
  },
  reaper: {
    key: "reaper",
    name: "Reaper",
    blurb: "Death incarnate. Massive damage, massive crit.",
    skin: "reaper",
    weapon: "railgun",
    hp: 90,
    speed: 285,
    damage: 1.45,
    turrets: 0,
    turretWeapon: "pistol",
    crit: 0.15,
    lifesteal: 0,
    hpMult: 1,
    speedMult: 1.02,
    damageMult: 1.45,
    startingMaterials: 0,
    color: "#c77dff",
    buffs: [
      { label: "Damage", value: "+45%", tone: "good" },
      { label: "Crit", value: "+15%", tone: "good" },
      { label: "Speed", value: "+2%", tone: "good" },
    ],
  },
};

export const CLASS_KEYS: ClassKey[] = Object.keys(CLASSES) as ClassKey[];

export function classForSkin(skin: CharacterKey): ClassKey {
  const match = CLASS_KEYS.find((k) => CLASSES[k].skin === skin);
  return match ?? "soldier";
}
